# Generated by Django 4.0.4 on 2022-06-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
