# Generated by Django 4.0.4 on 2022-06-01 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0002_alter_track_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message="Name's len must be more than 2")]),
        ),
    ]
