# Generated by Django 4.0.4 on 2022-06-16 12:52

import discography.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discography', '0002_rename_comment_text_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['date_published']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='discography.comment'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='date_published',
            field=models.DateField(validators=[discography.models.validate_date_published]),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('name', 'artist')},
        ),
    ]
